name: Dependabot Auto-Merge

on:
  pull_request:

permissions: read-all

jobs:
  automerge:
    name: Auto-Merge Patch Updates
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve and auto-merge patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --auto --squash
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
